<a href="https://colab.research.google.com/github/deric0118/DST3/blob/main/DST3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array1=np.zeros((2,2))
print(array1)

[[0. 0.]
 [0. 0.]]


In [3]:
array2=np.random.randint(10,size=(3,4))
print(array2)

[[3 0 0 3]
 [4 6 0 0]
 [9 4 5 3]]


In [4]:
array3a=np.ones((2,2))
print(array3a)

[[1. 1.]
 [1. 1.]]


In [5]:
array3b=np.zeros((2,2))
print(array3b)

[[0. 0.]
 [0. 0.]]


In [6]:
array4=np.random.randint(10,size=(6,3))
array4_transpose=array4.transpose()
print(array4)
print(array4_transpose)

[[8 8 1]
 [8 6 8]
 [4 6 7]
 [8 2 0]
 [0 5 9]
 [1 1 4]]
[[8 8 4 8 0 1]
 [8 6 6 2 5 1]
 [1 8 7 0 9 4]]


In [7]:
array5a=np.random.randint(10,size=(2,3))
array5b=np.random.randint(10,size=(3,4))
dot5=np.dot(array5a,array5b)
print(dot5)

[[104  72  61  18]
 [ 81  54  57  18]]
